### ISSUE TITLE
incorrect syntax u r missing double quotes around a string lawl

### ISSUE THREAD

**Issue by interesting84** [JimCTheProCoder/Python-HELLO-WRLD#2]

**Comment by interesting84** [comment]
@JimCTheProCoder

**Comment by longwatermelon** [comment]
Already Fixed You Absolute Noob LAWLALWAWLAWLAWLAWL

**Comment by Ay-355** [comment]
breh how dumb are you, did you not see my issue where he said thats how its supposed to be

**Comment by longwatermelon** [comment]
No I Dont think Interesting84 the Literal Buffoon Saw that

**Comment by JimCTheProCoder** [comment]
UwU
